# Generated by Django 2.2.13 on 2020-06-17 16:22

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100, verbose_name='Тип статьи')),
            ],
            options={
                'verbose_name': 'Тип статьи',
                'verbose_name_plural': '2 - Типы статей',
            },
        ),
        migrations.CreateModel(
            name='Blagodarnosti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год - в формате 4 цифр')),
            ],
            options={
                'verbose_name': 'Благодарности',
                'verbose_name_plural': '4 - Благодарности',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование файла на сайте')),
                ('file', models.FileField(blank=True, upload_to='files/', verbose_name='Файл')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления файла')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': '3 - Документы',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование проекта')),
                ('logo', models.ImageField(blank=True, upload_to='images/logos/', verbose_name='Логотип')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание на главной')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('videolink', models.TextField(blank=True, null=True, verbose_name='Идентификатор в ссылке на видео Youtube')),
                ('color', models.CharField(choices=[('1', 'Белый'), ('2', 'Синий')], max_length=50, verbose_name='Фон карточки проекта на Главной')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': '5 - Проекты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailto', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None, verbose_name='Почта, для уведомлений обратной связи')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name="Телефон 'Контакты' на главной")),
                ('contact_email', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name="Email 'Контакты' на главной")),
                ('contact_address', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name="Адрес 'Контакты' на главной")),
                ('contact_map', models.TextField(blank=True, default='', null=True, verbose_name='Ссылка на адрес в google maps')),
                ('requisites', models.TextField(blank=True, default='', null=True, verbose_name='Реквизиты')),
                ('banner_text', models.TextField(blank=True, default='Добро пожаловать!', null=True, verbose_name='Текст бегущей строки')),
                ('about_text', models.TextField(blank=True, default='', null=True, verbose_name="Текст 'О нас' на главной")),
                ('metadescr', models.TextField(blank=True, default='', null=True, verbose_name='Meta Description')),
                ('metakeywords', models.TextField(blank=True, default='', null=True, verbose_name='Meta Keyword')),
                ('default_newscover', models.ImageField(blank=True, upload_to='images/covers/', verbose_name='Обложка статьи по умолчанию')),
                ('default_videocover', models.ImageField(blank=True, upload_to='images/covers/', verbose_name='Обложка видео по умолчанию')),
                ('ig', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='User id аккаунта в Instagram')),
                ('vk', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='User id аккаунта в Вконтакте')),
                ('ok', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='User id аккаунта в Одноклассники')),
                ('yt', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='User id аккаунта в Youtube')),
                ('fb', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='User id аккаунта в Facebook')),
                ('tw', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='User id аккаунта в Twitter')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': '6 - Настройки',
            },
        ),
        migrations.CreateModel(
            name='BPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/articles/', verbose_name='Фотографии (одна или несколько)')),
                ('article', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.Blagodarnosti', verbose_name='Благодарности')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publish', models.DateTimeField(verbose_name='Дата публикации статьи')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок статьи')),
                ('cover', models.FileField(blank=True, upload_to='images/covers/', verbose_name='Обложка статьи')),
                ('content', models.TextField(verbose_name='Содержание (текст) статьи')),
                ('videolink', models.TextField(blank=True, null=True, verbose_name='Ссылка на видео (одно)')),
                ('kind', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='front.ArticleKind', verbose_name='Тип статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': '1 - Статьи',
                'ordering': ['-date_publish'],
            },
        ),
        migrations.CreateModel(
            name='APhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/articles/', verbose_name='Фотографии (одна или несколько)')),
                ('article', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.Article', verbose_name='Статья')),
            ],
        ),
    ]
