# Generated by Django 2.2.13 on 2020-06-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='default_videocover',
        ),
    ]
