# Generated by Django 2.2.13 on 2020-06-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20200622_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='contact_address',
            field=models.TextField(blank=True, default='', null=True, verbose_name="Адрес 'Контакты' на главной"),
        ),
    ]
