# Generated by Django 2.2.13 on 2020-06-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20200622_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlekind',
            options={'ordering': ['pk'], 'verbose_name': 'Тип статьи', 'verbose_name_plural': '2 - Типы статей'},
        ),
        migrations.AddField(
            model_name='projects',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True, unique=True, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='about_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name="Текст 'О Фонде' на главной"),
        ),
    ]
