# Generated by Django 2.2.13 on 2020-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20200623_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['order'], 'verbose_name': 'Проект', 'verbose_name_plural': '5 - Проекты'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/logos/', verbose_name='Логотип (оптимальная высота 180px +-20px)'),
        ),
    ]
