# Generated by Django 2.2.13 on 2020-06-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20200623_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='photo_amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество отображаемых фото в разделе проекта'),
        ),
        migrations.AddField(
            model_name='settings',
            name='default_videocover',
            field=models.ImageField(blank=True, upload_to='images/covers/', verbose_name='Обложка видео по умолчанию'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='color',
            field=models.CharField(choices=[('1', 'Белый'), ('2', 'Синий')], max_length=10, verbose_name='Фон карточки проекта на Главной'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Порядок отображения'),
        ),
    ]
