# Generated by Django 2.2.13 on 2020-06-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_projects_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='directory',
        ),
    ]
