# Generated by Django 2.2.13 on 2020-06-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_remove_projects_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bphoto',
            name='photo',
            field=models.ImageField(upload_to='images/blagodarnosti/', verbose_name='Фотографии (одна или несколько)'),
        ),
    ]
