# Generated by Django 2.2.13 on 2020-06-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_auto_20200624_0612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': '1 - Статьи'},
        ),
        migrations.RenameField(
            model_name='bphoto',
            old_name='article',
            new_name='year',
        ),
    ]
