# Generated by Django 2.2.13 on 2020-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_auto_20200624_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.TextField(verbose_name='Наименование файла на сайте'),
        ),
    ]
