# Generated by Django 2.2.13 on 2020-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_auto_20200624_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='videolink',
            field=models.TextField(blank=True, null=True, verbose_name='Идентификатор в ссылке на видео Youtube'),
        ),
    ]
