# Generated by Django 2.2.13 on 2020-06-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_auto_20200624_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'новость', 'verbose_name_plural': '1 - новости'},
        ),
        migrations.AlterModelOptions(
            name='articlekind',
            options={'ordering': ['pk'], 'verbose_name': 'Тип новости', 'verbose_name_plural': '2 - Типы новости'},
        ),
        migrations.AlterField(
            model_name='aphoto',
            name='article',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.Article', verbose_name='Новости'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание (текст) новости'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.FileField(blank=True, upload_to='images/covers/', verbose_name='Обложка новости'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_publish',
            field=models.DateTimeField(verbose_name='Дата публикации новости'),
        ),
        migrations.AlterField(
            model_name='article',
            name='kind',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='front.ArticleKind', verbose_name='Тип новости'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок новости'),
        ),
        migrations.AlterField(
            model_name='articlekind',
            name='kind',
            field=models.CharField(max_length=100, verbose_name='Тип новости'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_newscover',
            field=models.ImageField(blank=True, upload_to='images/covers/', verbose_name='Обложка новости по умолчанию'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fb',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ссылка на аккаунт в Facebook'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='ig',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ссылка на аккаунт в Instagram'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='ok',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ссылка на аккаунт в Одноклассники'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tw',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ссылка на аккаунт в Twitter'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='vk',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ссылка на аккаунт в Вконтакте'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='yt',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ссылка на аккаунт в Youtube'),
        ),
    ]
