# Generated by Django 2.2.13 on 2020-06-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_auto_20200626_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Новость', 'verbose_name_plural': '1 - Новости'},
        ),
    ]
